name: Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9']

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install torch numpy matplotlib pytest pytest-json-report pandas
    
    - name: Test Combined Diff
      run: |
        pytest test/test_combined_diff.py -v --tb=short
      continue-on-error: true
    
    - name: Test Modified Euler
      run: |
        pytest test/test_dff_modified_euler.py -v --tb=short
      continue-on-error: true
        
    - name: Test NorSand Functions
      run: |
        pytest test/test_diff_norsand_fn.py -v --tb=short
      continue-on-error: true
        
    - name: Test Pegasus
      run: |
        pytest test/test_diff_pegasus.py -v --tb=short
      continue-on-error: true
        
    - name: Test Stress Correction
      run: |
        pytest test/test_diff_stress_correction.py -v --tb=short
      continue-on-error: true
        
    - name: Test Diff Utils
      run: |
        pytest test/test_diff_utils.py -v --tb=short
      continue-on-error: true

    - name: Run All Tests
      run: |
        pytest test/ -v --json-report --json-report-file=test-results.json
      continue-on-error: true

    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results-${{ matrix.python-version }}
        path: test-results.json 